### ISSUE TITLE
Videocall

### ISSUE THREAD

**Issue by yrflxramalho** [sezerkorkmaz/cordova-plugin-sip#20]
Hi,

I tried make a video call, but it crash my app, is there someone with the same error?

"cordova.plugins.sip.videocall('adress', 'displayName', sipManager.events, sipManager.events);"

**Comment by yrflxramalho** [comment]
Process: io.cordova.hellocordova, PID: 7886
    java.lang.RuntimeException: Unable to resume activity {io.cordova.hellocordova/com.sip.linphone.LinphoneMiniActivity}: java.lang.RuntimeException: [Platform Helper] Rendering window id is not an instance of TextureView.Please update your UI layer so that the video rendering view is a TextureView (or an instance of it)or enable compatibility mode by setting displaytype=MSAndroidOpenGLDisplay in the [video] section your linphonerc factory configuration fileso you can keep using your existing application code for managing video views.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4255)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4287)
